 * Serving Flask app "catalog_v1" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 124-097-104
 * Serving Flask app "catalog_v1" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "catalog_v1.py", line 93, in <module>
    app.run(host='0.0.0.0')
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [22/Jan/2021 19:12:28] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:12:29] "[37mGET /static/background.png HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:12:31] "[33mGET /favicon.ico HTTP/1.0[0m" 404 -
127.0.0.1 - - [22/Jan/2021 19:12:47] "[37mGET /api/v1/resources/cursanti?grupa=Grupa1&profesoara=Loreta HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:12:48] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:12:57] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:13:02] "[37mGET /api/v1/resources/cursanti?grupa=Grupa1&profesoara=Loreta HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:13:03] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:13:26] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:13:33] "[37mGET /api/v1/resources/cursanti?grupa=Grupa1&profesoara=Loreta HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:14:04] "[37mGET / HTTP/1.0[0m" 200 -
127.0.0.1 - - [22/Jan/2021 19:37:39] "[37mGET / HTTP/1.0[0m" 200 -
